// Generated by uniffi-bindgen-react-native
#include "react-native-payjoin.h"
#include "generated/payjoin_ffi.hpp"

namespace payjoinsdk {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativePayjoinFfi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}
