// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-payjoin.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNPayjoinReactNativeSpec.h"

@interface PayjoinSdk : NSObject <NativePayjoinSdkSpec>
#else
#import <React/RCTBridgeModule.h>

@interface PayjoinSdk : NSObject <RCTBridgeModule>
#endif

@end
